print ("check")
print ("pleas enter the following information")
first=input("first name:")
last=input("last name:")
email=input("email address:")
id_number=input("yuor Id number:")
print()
print("\n your information is")
print(f" Name:{first.upper()}  {last.capitalize()}")
print(f"email:{email.lower()}")
print(f"Idnumber:{id_number}")